const hre = require("hardhat");
const fs = require('fs');
const path = require('path');

async function main() {
  console.log("🚀 Deploying Updated TokenizationManager...\n");

  // Get the deployer account
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  
  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", hre.ethers.formatEther(balance), "ETH\n");

  // Deploy TokenizationManager (which also deploys PropertyDeed)
  console.log("�� Deploying TokenizationManager...");
  const TokenizationManager = await hre.ethers.getContractFactory("TokenizationManager");
  const tokenizationManager = await TokenizationManager.deploy();
  await tokenizationManager.waitForDeployment();
  
  const tokenizationManagerAddress = await tokenizationManager.getAddress();
  console.log("✅ TokenizationManager deployed to:", tokenizationManagerAddress);

  // Get PropertyDeed address from TokenizationManager
  const propertyDeedAddress = await tokenizationManager.propertyDeedContract();
  console.log("✅ PropertyDeed deployed to:", propertyDeedAddress);

  // Deploy a sample PropertyFractions (for ABI generation)
  console.log("\n📝 Deploying sample PropertyFractions for ABI...");
  const PropertyFractions = await hre.ethers.getContractFactory("PropertyFractions");
  const propertyFractions = await PropertyFractions.deploy(1, tokenizationManagerAddress);
  await propertyFractions.waitForDeployment();
  
  const propertyFractionsAddress = await propertyFractions.getAddress();
  console.log("✅ Sample PropertyFractions deployed to:", propertyFractionsAddress);

  // Save deployment info
  const deploymentInfo = {
    network: hre.network.name,
    tokenizationManager: tokenizationManagerAddress,
    propertyDeed: propertyDeedAddress,
    propertyFractions: propertyFractionsAddress,
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    blockNumber: await hre.ethers.provider.getBlockNumber()
  };

  const infoPath = path.join(__dirname, '..', 'deployment-info.json');
  fs.writeFileSync(infoPath, JSON.stringify(deploymentInfo, null, 2));
  console.log("\n📄 Deployment info saved to:", infoPath);

  // Generate frontend config
  const frontendDir = path.join(__dirname, '..', 'frontend', 'src', 'contracts');
  if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
  }

  // Get ABIs
  const TokenizationManagerArtifact = await hre.artifacts.readArtifact("TokenizationManager");
  const PropertyDeedArtifact = await hre.artifacts.readArtifact("PropertyDeed");
  const PropertyFractionsArtifact = await hre.artifacts.readArtifact("PropertyFractions");

  const config = `// Auto-generated by deployment script
// DO NOT EDIT MANUALLY

export const ADDRESSES = {
  TOKENIZATION_MANAGER: '${tokenizationManagerAddress}',
  PROPERTY_DEED: '${propertyDeedAddress}',
  PROPERTY_FRACTIONS: '${propertyFractionsAddress}', // Sample contract for reference
};

export const TOKENIZATION_MANAGER_ABI = ${JSON.stringify(TokenizationManagerArtifact.abi, null, 2)};

export const PROPERTY_DEED_ABI = ${JSON.stringify(PropertyDeedArtifact.abi, null, 2)};

export const PROPERTY_FRACTIONS_ABI = ${JSON.stringify(PropertyFractionsArtifact.abi, null, 2)};
`;

  const configPath = path.join(frontendDir, 'abis.js');
  fs.writeFileSync(configPath, config);
  console.log("✅ Frontend config saved to:", configPath);

  console.log("\n🎉 Deployment Complete!\n");
  console.log("📋 Contract Addresses:");
  console.log("   TokenizationManager:", tokenizationManagerAddress);
  console.log("   PropertyDeed:", propertyDeedAddress);
  console.log("   PropertyFractions (sample):", propertyFractionsAddress);
  console.log("\n⚠️  IMPORTANT: Update your frontend .env file with these addresses!");
  console.log("\n✅ Key Changes in this deployment:");
  console.log("   1. PropertyDeed NFT is minted to TokenizationManager (already locked)");
  console.log("   2. No NFT transfer needed in startDistribution");
  console.log("   3. Owner approves PropertyFractions ERC20 tokens for sale");
  console.log("   4. Anyone can buy fractions once distribution starts");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
